// import Head from "next/head";
import { getFeaturedEvents } from '@/helpers/api-util';
import EventList from '@/components/events/EventList/EventList';
import s from './index.module.scss';
interface Events {
  id: string;
  date: string;
  description: string;
  image: string;
  isFeatured: boolean;
  location: string;
  title: string;
}

export default function Home({ events }: { events: Events[] }) {
  return (
    <>
      {/* <Head>
        <title>Events | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <EventList events={events} />
    </>
  );
}

export async function getStaticProps() {
  const featuredEvents = await getFeaturedEvents();

  return {
    props: {
      events: featuredEvents,
    },
    revalidate: 1800,
  };
}
